version: '3'

volumes:
  storyland_local_postgres_data: {}
  storyland_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: storyland_local_django
    container_name: storyland_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: storyland_production_postgres
    container_name: storyland_local_postgres
    volumes:
      - storyland_local_postgres_data:/var/lib/postgresql/data
      - storyland_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: storyland_local_docs
    container_name: storyland_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./storyland:/app/storyland:z
      - ./rewards:/app/rewards:z
    ports:
      - '9000:9000'
    command: /start-docs

  vite:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: my_awesome_vue_project_local_vite
    container_name: my_awesome_vue_project_local_vite
    depends_on:
      - django
    volumes:
      - .:/app:z
      - /app/vue_frontend/node_modules
    command: vite dev
    ports:
      - '5173:5173'
